using System.Globalization;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using EmpactRecipeOnline.Models;

namespace EmpactRecipeOnline.Services;

public sealed class NutritionService(HttpClient http, JsonDataStore store, IConfiguration configuration, IWebHostEnvironment env)
{
    private readonly string _apiKey = configuration["Nutrition:FoodDataCentralApiKey"]?.Trim() is { Length: > 0 } key ? key : "DEMO_KEY";
    private readonly bool _autoLookupEnabled = !string.Equals(configuration["Nutrition:AutoLookupEnabled"], "false", StringComparison.OrdinalIgnoreCase);
    private readonly bool _allowUsdaFallback = !string.Equals(configuration["Nutrition:AllowUsdaFallback"], "false", StringComparison.OrdinalIgnoreCase);
    private readonly string _safoodsPath = Path.Combine(env.ContentRootPath, "App_Data", configuration["Nutrition:SafoodsFileName"]?.Trim() is { Length: > 0 } f ? f : "safoods-nutrition.csv");

    public RecipeNutritionAnalysisResult CalculateFromCache(Recipe recipe, int portions)
    {
        var safePortions = Math.Max(1, portions);
        var result = new RecipeNutritionAnalysisResult { Portions = safePortions };
        foreach (var line in recipe.Ingredients)
        {
            var key = NormalizeIngredientKey(line);
            var profile = store.Data.NutritionProfiles.FirstOrDefault(x => x.IngredientKey.Equals(key, StringComparison.OrdinalIgnoreCase));
            result.Ingredients.Add(CalculateLine(recipe, line, profile, safePortions));
        }
        return result;
    }

    public async Task<RecipeNutritionAnalysisResult> GenerateAsync(Recipe recipe, CancellationToken cancellationToken = default)
    {
        store.Data.NutritionProfiles ??= new List<NutritionProfile>();
        foreach (var line in recipe.Ingredients)
        {
            var key = NormalizeIngredientKey(line);
            if (string.IsNullOrWhiteSpace(key)) continue;
            var existing = store.Data.NutritionProfiles.FirstOrDefault(x => x.IngredientKey.Equals(key, StringComparison.OrdinalIgnoreCase));
            // When a licensed SAFOODS file is present, a refresh upgrades older USDA/unmapped cache entries to the South African source.
            if (existing is not null && existing.SourceSystem.StartsWith("SAFOODS", StringComparison.OrdinalIgnoreCase)) continue;

            NutritionProfile? profile = TryLookupSafoodsLocal(line);
            if (profile is null && existing is not null && existing.FoodDataCentralId.HasValue) continue;
            if (profile is null && _autoLookupEnabled && _allowUsdaFallback)
            {
                try { profile = await LookupFoodDataCentralAsync(line, cancellationToken); }
                catch { /* Keep the recipe usable if an external nutrition lookup is unavailable. */ }
            }
            profile ??= new NutritionProfile
            {
                IngredientKey = key,
                IngredientDisplayName = line.Name,
                SourceSystem = "Unmapped",
                SourceFoodName = "Nutrition reference not yet mapped",
                MatchConfidencePercent = 0,
                RequiresReview = true
            };
            if (existing is not null) store.Data.NutritionProfiles.Remove(existing);
            store.Data.NutritionProfiles.Add(profile);
        }

        // Nutrition is always analysed for exactly one finished portion.
        var analysis = CalculateFromCache(recipe, 1);
        recipe.EnergyKcalPerPortion = analysis.EnergyKcalTotal;
        recipe.EnergyKjPerPortion = analysis.EnergyKjTotal;
        recipe.ProteinGramsPerPortion = analysis.ProteinGramsTotal;
        recipe.CarbohydrateGramsPerPortion = analysis.CarbohydrateGramsTotal;
        recipe.SugarGramsPerPortion = analysis.SugarGramsTotal;
        recipe.FatGramsPerPortion = analysis.FatGramsTotal;
        recipe.SaturatedFatGramsPerPortion = analysis.SaturatedFatGramsTotal;
        recipe.FibreGramsPerPortion = analysis.FibreGramsTotal;
        recipe.SodiumMgPerPortion = analysis.SodiumMgTotal;
        recipe.NutritionVerified = false;
        recipe.NutritionAutoGenerated = true;
        recipe.NutritionGeneratedAtUtc = DateTime.UtcNow;
        recipe.NutritionCoveragePercent = analysis.CoveragePercent;
        recipe.NutritionSourceNote = File.Exists(_safoodsPath)
            ? "Automatically estimated for one finished portion using the locally licensed South African SAFOODS reference file first. Any unmatched ingredient may use the configured USDA fallback and is clearly identified in the ingredient breakdown."
            : "Automatically estimated for one finished portion. A licensed SAFOODS nutrition file has not yet been loaded, so unmatched ingredients use the configured USDA fallback. Add the licensed SAFOODS export to App_Data/safoods-nutrition.csv for South-African-first matching.";
        store.Save();
        return analysis;
    }

    private NutritionProfile? TryLookupSafoodsLocal(IngredientLine line)
    {
        if (!File.Exists(_safoodsPath)) return null;
        var query = CleanSearchName(line.Name);
        if (string.IsNullOrWhiteSpace(query)) return null;
        try
        {
            var rows = File.ReadLines(_safoodsPath).Where(x => !string.IsNullOrWhiteSpace(x)).ToList();
            if (rows.Count < 2) return null;
            var headers = ParseCsvLine(rows[0]);
            int Col(params string[] names)
            {
                for (var i = 0; i < headers.Count; i++)
                    if (names.Any(n => headers[i].Trim().Equals(n, StringComparison.OrdinalIgnoreCase))) return i;
                return -1;
            }
            var nameCol = Col("FoodName", "Food Name", "Description", "Food");
            if (nameCol < 0) return null;
            var codeCol = Col("FoodCode", "Food Code", "Code");
            var candidates = new List<(List<string> Cells, decimal Score)>();
            foreach (var row in rows.Skip(1))
            {
                var cells = ParseCsvLine(row);
                if (cells.Count <= nameCol) continue;
                var score = ScoreCandidate(query, cells[nameCol], "SAFOODS");
                if (score > 0) candidates.Add((cells, score));
            }
            var best = candidates.OrderByDescending(x => x.Score).FirstOrDefault();
            if (best.Cells is null || best.Score < 55m) return null;
            decimal Num(params string[] names)
            {
                var c = Col(names);
                if (c < 0 || c >= best.Cells.Count) return 0m;
                var v = best.Cells[c].Trim().Replace(',', '.');
                return decimal.TryParse(v, NumberStyles.Any, CultureInfo.InvariantCulture, out var n) ? n : 0m;
            }
            var kcal = Num("EnergyKcalPer100g", "Energy kcal/100g", "Energy kcal");
            var kj = Num("EnergyKjPer100g", "Energy kJ/100g", "Energy kJ");
            if (kj <= 0 && kcal > 0) kj = kcal * 4.184m;
            if (kcal <= 0 && kj > 0) kcal = kj / 4.184m;
            return new NutritionProfile
            {
                IngredientKey = NormalizeIngredientKey(line),
                IngredientDisplayName = line.Name,
                SourceSystem = "SAFOODS (SAMRC)",
                SourceReferenceCode = codeCol >= 0 && codeCol < best.Cells.Count ? best.Cells[codeCol] : string.Empty,
                SourceFoodName = best.Cells[nameCol],
                SourceDataType = "South African Food Composition Database",
                EnergyKcalPer100g = kcal,
                EnergyKjPer100g = kj,
                ProteinGramsPer100g = Num("ProteinGramsPer100g", "Protein g/100g", "Protein"),
                CarbohydrateGramsPer100g = Num("CarbohydrateGramsPer100g", "Carbohydrate g/100g", "Carbohydrate"),
                SugarGramsPer100g = Num("SugarGramsPer100g", "Sugar g/100g", "Total Sugar", "Sugar"),
                FatGramsPer100g = Num("FatGramsPer100g", "Fat g/100g", "Total Fat", "Fat"),
                SaturatedFatGramsPer100g = Num("SaturatedFatGramsPer100g", "Saturated Fat g/100g", "Saturated Fat"),
                FibreGramsPer100g = Num("FibreGramsPer100g", "Fibre g/100g", "Fibre", "Fiber"),
                SodiumMgPer100g = Num("SodiumMgPer100g", "Sodium mg/100g", "Sodium"),
                MatchConfidencePercent = Math.Clamp(best.Score, 0m, 100m),
                RequiresReview = best.Score < 82m,
                Verified = false,
                UpdatedAtUtc = DateTime.UtcNow
            };
        }
        catch { return null; }
    }

    private static List<string> ParseCsvLine(string line)
    {
        var result = new List<string>();
        var current = new System.Text.StringBuilder();
        var quoted = false;
        for (var i = 0; i < line.Length; i++)
        {
            var ch = line[i];
            if (ch == '"')
            {
                if (quoted && i + 1 < line.Length && line[i + 1] == '"') { current.Append('"'); i++; }
                else quoted = !quoted;
            }
            else if (ch == ',' && !quoted) { result.Add(current.ToString()); current.Clear(); }
            else current.Append(ch);
        }
        result.Add(current.ToString());
        return result;
    }

    private async Task<NutritionProfile?> LookupFoodDataCentralAsync(IngredientLine line, CancellationToken cancellationToken)
    {
        var query = CleanSearchName(line.Name);
        if (string.IsNullOrWhiteSpace(query)) return null;
        var url = $"https://api.nal.usda.gov/fdc/v1/foods/search?api_key={Uri.EscapeDataString(_apiKey)}&query={Uri.EscapeDataString(query)}&pageSize=8";
        var response = await http.GetFromJsonAsync<FdcSearchResponse>(url, cancellationToken);
        var candidates = response?.Foods ?? new List<FdcFood>();
        if (candidates.Count == 0) return null;

        var scored = candidates
            .Select(x => new { Food = x, Score = ScoreCandidate(query, x.Description, x.DataType) })
            .OrderByDescending(x => x.Score)
            .First();
        var chosen = scored.Food;
        var nutrients = chosen.FoodNutrients ?? new List<FdcNutrient>();
        decimal Get(params string[] names)
        {
            var item = nutrients.FirstOrDefault(n => names.Any(name => n.NutrientName.Contains(name, StringComparison.OrdinalIgnoreCase)));
            return item?.Value ?? 0m;
        }
        var kcal = nutrients.FirstOrDefault(n => n.NutrientName.Contains("Energy", StringComparison.OrdinalIgnoreCase) && n.UnitName.Equals("kcal", StringComparison.OrdinalIgnoreCase))?.Value ?? 0m;
        var kj = nutrients.FirstOrDefault(n => n.NutrientName.Contains("Energy", StringComparison.OrdinalIgnoreCase) && n.UnitName.Equals("kJ", StringComparison.OrdinalIgnoreCase))?.Value ?? 0m;
        if (kj <= 0 && kcal > 0) kj = kcal * 4.184m;

        return new NutritionProfile
        {
            IngredientKey = NormalizeIngredientKey(line),
            IngredientDisplayName = line.Name,
            FoodDataCentralId = chosen.FdcId,
            SourceSystem = "USDA FoodData Central",
            SourceReferenceCode = chosen.FdcId.ToString(CultureInfo.InvariantCulture),
            SourceFoodName = chosen.Description,
            SourceDataType = chosen.DataType,
            EnergyKcalPer100g = kcal,
            EnergyKjPer100g = kj,
            ProteinGramsPer100g = Get("Protein"),
            CarbohydrateGramsPer100g = Get("Carbohydrate, by difference", "Carbohydrate"),
            SugarGramsPer100g = Get("Sugars, total", "Total Sugars"),
            FatGramsPer100g = Get("Total lipid (fat)", "Total lipid"),
            SaturatedFatGramsPer100g = Get("Fatty acids, total saturated", "Saturated"),
            FibreGramsPer100g = Get("Fiber, total dietary", "Fibre", "Fiber"),
            SodiumMgPer100g = Get("Sodium"),
            MatchConfidencePercent = Math.Clamp(scored.Score, 0m, 100m),
            RequiresReview = scored.Score < 82m,
            Verified = false,
            UpdatedAtUtc = DateTime.UtcNow
        };
    }

    private static IngredientNutritionContribution CalculateLine(Recipe recipe, IngredientLine line, NutritionProfile? profile, int portions)
    {
        var issue = line.GetBatchIssue(recipe.EffectiveBasePortions, portions);
        var contribution = new IngredientNutritionContribution
        {
            IngredientName = line.Name,
            ProductCode = line.ProductCode,
            RecipeQuantity = issue,
            RecipeUnit = line.Unit,
            SourceSystem = profile?.SourceSystem ?? string.Empty,
            SourceReferenceCode = profile?.SourceReferenceCode ?? string.Empty,
            SourceFoodName = profile?.SourceFoodName ?? "Not mapped",
            FoodDataCentralId = profile?.FoodDataCentralId,
            RequiresReview = profile?.RequiresReview ?? true
        };
        if (profile is null || profile.FoodDataCentralId is null)
        {
            contribution.Note = "No nutrition reference match. Generate or review this ingredient mapping.";
            return contribution;
        }
        var grams = ConvertToGrams(issue, line.Unit, line.PackSize, profile, out var note, out var conversionReview);
        contribution.EstimatedGrams = grams;
        contribution.RequiresReview |= conversionReview;
        contribution.Note = note;
        if (!grams.HasValue || grams <= 0) return contribution;

        var factor = grams.Value / 100m;
        contribution.EnergyKcal = profile.EnergyKcalPer100g * factor;
        contribution.EnergyKj = profile.EnergyKjPer100g * factor;
        contribution.ProteinGrams = profile.ProteinGramsPer100g * factor;
        contribution.CarbohydrateGrams = profile.CarbohydrateGramsPer100g * factor;
        contribution.SugarGrams = profile.SugarGramsPer100g * factor;
        contribution.FatGrams = profile.FatGramsPer100g * factor;
        contribution.SaturatedFatGrams = profile.SaturatedFatGramsPer100g * factor;
        contribution.FibreGrams = profile.FibreGramsPer100g * factor;
        contribution.SodiumMg = profile.SodiumMgPer100g * factor;
        contribution.IncludedInTotal = true;
        return contribution;
    }

    private static decimal? ConvertToGrams(decimal quantity, string? unit, string? packSize, NutritionProfile profile, out string note, out bool review)
    {
        var u = (unit ?? string.Empty).Trim().ToUpperInvariant();
        note = string.Empty; review = false;
        if (u is "KG" or "KGS" or "KILOGRAM" or "KILOGRAMS") return quantity * 1000m;
        if (u is "G" or "GRAM" or "GRAMS") return quantity;
        if (u is "MG") return quantity / 1000m;
        if (u is "LT" or "L" or "LTR" or "LITRE" or "LITER" or "LITRES" or "LITERS")
        {
            var density = profile.GramsPerMillilitre ?? 1m;
            review = !profile.GramsPerMillilitre.HasValue;
            note = review ? "Volume converted using the default 1 g/ml assumption; verify density for this ingredient." : "Volume converted using the stored ingredient density.";
            return quantity * 1000m * density;
        }
        if (u is "ML" or "MILLILITRE" or "MILLILITER")
        {
            var density = profile.GramsPerMillilitre ?? 1m;
            review = !profile.GramsPerMillilitre.HasValue;
            note = review ? "Volume converted using the default 1 g/ml assumption; verify density for this ingredient." : "Volume converted using the stored ingredient density.";
            return quantity * density;
        }
        if (profile.GramsPerEach.HasValue)
        {
            note = "Count converted using the stored grams-per-unit value.";
            return quantity * profile.GramsPerEach.Value;
        }
        var packGrams = TryParsePackGrams(packSize);
        if (packGrams.HasValue)
        {
            review = true;
            note = "Count converted from the pack-size text; verify that one recipe unit equals one stated pack.";
            return quantity * packGrams.Value;
        }
        review = true;
        note = "A grams-per-unit conversion is required for this recipe unit before it can be included.";
        return null;
    }

    private static decimal? TryParsePackGrams(string? packSize)
    {
        if (string.IsNullOrWhiteSpace(packSize)) return null;
        var text = packSize.ToUpperInvariant().Replace(" ", "");
        var kg = Regex.Match(text, @"(?<v>\d+(?:[\.,]\d+)?)KG\b");
        if (kg.Success && decimal.TryParse(kg.Groups["v"].Value.Replace(',', '.'), NumberStyles.Any, CultureInfo.InvariantCulture, out var kgv)) return kgv * 1000m;
        var g = Regex.Match(text, @"(?<v>\d+(?:[\.,]\d+)?)G\b");
        if (g.Success && decimal.TryParse(g.Groups["v"].Value.Replace(',', '.'), NumberStyles.Any, CultureInfo.InvariantCulture, out var gv)) return gv;
        return null;
    }

    public static string NormalizeIngredientKey(IngredientLine line)
    {
        if (!string.IsNullOrWhiteSpace(line.ProductCode)) return "APL:" + line.ProductCode.Trim().ToUpperInvariant();
        return "NAME:" + Regex.Replace((line.Name ?? string.Empty).Trim().ToUpperInvariant(), @"\s+", " ");
    }

    private static string CleanSearchName(string? name)
    {
        var text = (name ?? string.Empty).ToLowerInvariant();
        text = Regex.Replace(text, @"\b\d+(?:[\.,]\d+)?\s*(kg|g|mg|l|lt|ml|each|ea|x)\b", " ");
        text = Regex.Replace(text, @"[^a-z\s]", " ");
        text = Regex.Replace(text, @"\b(fresh|frozen|chilled|bulk|pack|case|each|whole)\b", " ");
        return Regex.Replace(text, @"\s+", " ").Trim();
    }

    private static decimal ScoreCandidate(string query, string description, string dataType)
    {
        var q = query.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(x => x.ToLowerInvariant()).ToHashSet();
        var d = Regex.Replace((description ?? string.Empty).ToLowerInvariant(), @"[^a-z\s]", " ").Split(' ', StringSplitOptions.RemoveEmptyEntries).ToHashSet();
        var overlap = q.Count == 0 ? 0m : q.Count(d.Contains) * 100m / q.Count;
        var dataBonus = dataType.Contains("Foundation", StringComparison.OrdinalIgnoreCase) ? 8m : dataType.Contains("SR Legacy", StringComparison.OrdinalIgnoreCase) ? 6m : dataType.Contains("Survey", StringComparison.OrdinalIgnoreCase) ? 4m : 0m;
        return Math.Min(100m, overlap * 0.9m + dataBonus);
    }

    private static decimal PerPortion(decimal total, int portions) => portions <= 0 ? 0 : total / portions;

    private sealed class FdcSearchResponse { [JsonPropertyName("foods")] public List<FdcFood> Foods { get; set; } = new(); }
    private sealed class FdcFood
    {
        [JsonPropertyName("fdcId")] public long FdcId { get; set; }
        [JsonPropertyName("description")] public string Description { get; set; } = string.Empty;
        [JsonPropertyName("dataType")] public string DataType { get; set; } = string.Empty;
        [JsonPropertyName("foodNutrients")] public List<FdcNutrient> FoodNutrients { get; set; } = new();
    }
    private sealed class FdcNutrient
    {
        [JsonPropertyName("nutrientName")] public string NutrientName { get; set; } = string.Empty;
        [JsonPropertyName("unitName")] public string UnitName { get; set; } = string.Empty;
        [JsonPropertyName("value")] public decimal Value { get; set; }
    }
}
